apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: ouo-scheduler
    leaderElection:
      leaderElect: true
      lockObjectName: ouo-scheduler
      lockObjectNamespace: kube-system
    plugins:
      queueSort:
        enabled:
        - name: "ouo-scheduler"
    pluginConfig:
    - name: "ouo-scheduler"
      args: {"master": "master", "kubeconfig": "kubeconfig"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ouo-scheduler
  namespace: kube-system
  labels:
    component: ouo-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ouo-scheduler
  template:
    metadata:
      labels:
        component: ouo-scheduler
    spec:
      serviceAccount: ouo-sa
      priorityClassName: system-cluster-critical
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
      containers:
      - name: ouo-scheduler-pod
        image: ouo-scheduler:26da0b5
        imagePullPolicy: IfNotPresent
        args:
        - ouo-scheduler
        - --config=/scheduler/scheduler-config.yaml
        - --v=3
        resources:
          requests:
            cpu: "50m"
        volumeMounts:
        - name: scheduler-config
          mountPath: /scheduler
